#!/bin/bash
set -euxo pipefail

export REDIS_HOST=$(gcloud redis instances describe redisdb --region ${GOOGLE_CLOUD_REGION} --format "value(host)")
export REDIS_PORT=$(gcloud redis instances describe redisdb --region ${GOOGLE_CLOUD_REGION} --format "value(port)")
echo ${REDIS_HOST}
echo ${REDIS_PORT}